version: '3.8'

services:
  backend:
    image: aiprojects:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    working_dir: /app
    command: /bin/sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
